# Basement ESP8266MOD with BME280 attached.
#
# Wiring:   ESP8266MOD   BME280
#           3V3           VIN   (can also use 5V with the sensor I chose)
#           GND           GND
#   GPIO5   D1            SCL
#   GPIO4   D2            SDA

esphome:
  name: esphome-web-[redacted]
  friendly_name: Basement Temp

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[redacted]"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-[redacted]"
    password: "[redacted]"

captive_portal:

i2c:
  sda: 4
  scl: 5
  scan: True

# Example configuration entry
sensor:
  - platform: bme280_i2c
    temperature:
      id: temperature
      name: "Basement Temperature"
      oversampling: 16x
    pressure:
      name: "Basement Pressure"
      id: pressure
    humidity:
      name: "Basement Humidity"
      id: humidity
    address: 0x76
    update_interval: 20s


web_server:
  port: 80    